export async function uploadToSpaces(file: File, documentId: string): Promise<string> {
  const bucketName = import.meta.env.VITE_DO_BUCKET || "cadeveloper";
  const fileExtension = file.name.split('.').pop();
  const fileName = `ecc-docs/${documentId}.${fileExtension}`;
  
  // Construct the URL directly
  // Example: https://cadeveloper.nyc3.digitaloceanspaces.com/ecc-docs/DOC-123.jpg
  const endpoint = import.meta.env.VITE_DO_ENDPOINT || "nyc3.digitaloceanspaces.com";
  const cleanEndpoint = endpoint.replace('https://', '').replace(/\/$/, '');
  const uploadUrl = `https://${bucketName}.${cleanEndpoint}/${fileName}`;

  try {
    // Generate an incredibly simplified upload using native fetch.
    // NOTE: For true secure uploads from a browser, you MUST use a pre-signed URL generated by a backend.
    // However, since we are hardcoding keys in the frontend for this MVP, we 
    // will attempt a direct PUT. If DO requires strict AWS v4 signatures, this raw fetch will fail
    // and we will have to fallback to the AWS SDK, but we need to pass credentials differently.
    
    // Actually, Amazon S3 / DO Spaces REQUIRE requests to be signed. A simple fetch PUT will return 403.
    // Let's go back to S3Client but fix the configuration to pass validation.
    console.warn("Using AWS SDK for upload...");
    
    const { S3Client, PutObjectCommand } = await import("@aws-sdk/client-s3");
    
    const s3Client = new S3Client({
      endpoint: import.meta.env.VITE_DO_ENDPOINT?.startsWith('http') 
                  ? import.meta.env.VITE_DO_ENDPOINT 
                  : `https://${import.meta.env.VITE_DO_ENDPOINT || "nyc3.digitaloceanspaces.com"}`,
      region: "us-east-1", // Force AWS matching region
      forcePathStyle: false,
      credentials: {
        accessKeyId: import.meta.env.VITE_DO_ACCESS_KEY || "",
        secretAccessKey: import.meta.env.VITE_DO_SECRET || "",
      },
    });

    const buffer = await file.arrayBuffer();
    const command = new PutObjectCommand({
      Bucket: bucketName,
      Key: fileName,
      Body: new Uint8Array(buffer),
      ACL: "public-read",
      ContentType: file.type || 'application/pdf',
    });

    await s3Client.send(command);
    return uploadUrl;

  } catch (error) {
    console.error("Error real de subida a DO:", error);
    throw error;
  }
}
